version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
    environment:
      - SECRET_KEY=
      - ALLOWED_HOSTS=127.0.0.1,localhost
      - DEBUG=0

  proxy:
    build:
      context: ./proxy
    volumes:
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
    ports:
      - "8080:8080"
    depends_on:
      - app

volumes:
  static_volume:
  media_volume: